services:
  lexico:
    build:
      context: ./servicio-lexico
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - red_compilador
    env_file:
      - .env
    environment:
      - URL_SERVICIO_SINTACTICO=http://sintactico:8002
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - sintactico

  sintactico:
    build:
      context: ./servicio-sintactico
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - red_compilador
    env_file:
      - .env
    environment:
      - URL_SERVICIO_SEMANTICO=http://semantico:8003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - semantico

  semantico:
    build:
      context: ./servicio-semantico
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - red_compilador
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  red_compilador:
    driver: bridge
