version: '3.8'

services:
  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    # image: usuario_dockerhub/validador-api:v1.0 # (Descomentar para push a Docker Hub)
    # Exponemos ningún puerto hacia el exterior, solo Nginx puede hablar con "api" a través de la red interna.
    expose:
      - "8000"
    networks:
      - internal_network
    environment:
      # Si Ollama está corriendo en la máquina host (fuera de Docker), 
      # el contenedor puede comunicarse con él usando esta URL:
      - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Mapea el puerto 80 del host al 80 del contenedor Nginx (Puerto oculto en la URL)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
