events {
    worker_connections 1024;
}

http {
    # Definimos el grupo "api_backend" que apuntará a los contenedores
    # El nombre "api" coincide con el nombre del servicio en docker-compose
    # Docker se encarga de resolver "api" a todas las IPs de las réplicas mediante su DNS interno.
    upstream api_backend {
        server api:8000;
    }

    server {
        listen 80;
        
        # Nombre del servidor o dominio
        server_name Grupo4;

        location / {
            # Redirigir el tráfico hacia el grupo definido
            proxy_pass http://api_backend;
            
            # Pasar headers originales para que FastAPI sepa quién es el cliente real
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
